## By Catch Transfer

In [1]:
import polars as pl

from dataframe.miscellaneous import by_catch
from data_source.make_dataset import load_gsheet_data

In [2]:
bycatch_id :str ="1M_r_MuQo17Lg-9qbFxq8fREs3afKETLvkHclcWD9J_E"

bycatch_sheet :str="ByCatchTransfer"

In [3]:
transfer_of_bycatch_log = load_gsheet_data(
    bycatch_id,
    bycatch_sheet
).filter(pl.col("date").dt.year().eq(2025)).collect()

In [7]:
transfer_of_bycatch_log.filter(pl.col("date").dt.month().eq(5)).filter(pl.col("is_in_record").ne("OK"))

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ date      ┆ time_star ┆ time_stop ┆ vessel    ┆ … ┆ driver    ┆ truck_no ┆ is_in_rec ┆ whats_app │
│ ---       ┆ t         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---      ┆ ord       ┆ ---       │
│ date      ┆ ---       ┆ time      ┆ str       ┆   ┆ str       ┆ i64      ┆ ---       ┆ str       │
│           ┆ time      ┆           ┆           ┆   ┆           ┆          ┆ str       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 2025-05-0 ┆ 17:00:00  ┆ 18:45:00  ┆ PLAYA DE  ┆ … ┆ R.        ┆ 2        ┆ No        ┆ No        │
│ 7         ┆           ┆           ┆ RIS       ┆   ┆ Adeline   ┆          ┆ Data...   ┆ Message   │
│ 2025-05-1 ┆ 18:00:00  ┆ 18:32:00  ┆ TXORI     ┆ … ┆ J. Idrice ┆ 8        ┆ No        ┆ No        │
│ 4         ┆           ┆           ┆ BERRI     ┆   ┆           ┆          ┆ Data...   ┆ Message   │
│ 2025-05-1 ┆ 12:30:00  ┆ 18:50:00  ┆ ALBACORA  ┆ … ┆ R.        ┆ 2        ┆ No        ┆ No        │
│ 5         ┆           ┆           ┆ CUATRO    ┆   ┆ Adeline   ┆          ┆ Data...   ┆ Message   │
│ 2025-05-1 ┆ 17:05:00  ┆ 17:35:00  ┆ ADAMAS    ┆ … ┆ B.        ┆ 7        ┆ No        ┆ No        │
│ 6         ┆           ┆           ┆           ┆   ┆ Bamboche  ┆          ┆ Data...   ┆ Message   │
│ 2025-05-2 ┆ 17:22:00  ┆ 17:32:00  ┆ FRANCHE   ┆ … ┆ B.        ┆ 7        ┆ No        ┆ No        │
│ 0         ┆           ┆           ┆ TERRE     ┆   ┆ Bamboche  ┆          ┆ Data...   ┆ Message   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [5]:
transfer_of_bycatch = by_catch.filter(pl.col("operation_type").eq(pl.lit("Transfer of by-catch"))).collect()

In [6]:
transfer_of_bycatch.filter(pl.col("date").dt.month().eq(4))

shape: (70, 9)
┌──────┬────────────┬─────────────┬─────────────┬───┬────────────┬────────────┬───────┬────────────┐
│ day  ┆ date       ┆ customer    ┆ vessel      ┆ … ┆ total_tonn ┆ overtime_t ┆ Price ┆ total_pric │
│ ---  ┆ ---        ┆ ---         ┆ ---         ┆   ┆ age        ┆ onnage     ┆ ---   ┆ e          │
│ enum ┆ date       ┆ str         ┆ str         ┆   ┆ ---        ┆ ---        ┆ f64   ┆ ---        │
│      ┆            ┆             ┆             ┆   ┆ f64        ┆ f64        ┆       ┆ f64        │
╞══════╪════════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪═══════╪════════════╡
│ Tue  ┆ 2024-04-02 ┆ OCEAN       ┆ BERNICA     ┆ … ┆ 1.585      ┆ 0.0        ┆ 7.5   ┆ 11.8875    │
│      ┆            ┆ BASKET      ┆             ┆   ┆            ┆            ┆       ┆            │
│ Fri  ┆ 2024-04-05 ┆ OCEAN       ┆ BERNICA     ┆ … ┆ 17.638     ┆ 0.0        ┆ 7.5   ┆ 132.285    │
│      ┆            ┆ BASKET      ┆             ┆   ┆            ┆            ┆       ┆            │
│ Wed  ┆ 2024-04-10 ┆ OCEAN       ┆ CAP SAINTE  ┆ … ┆ 2.131      ┆ 0.0        ┆ 7.5   ┆ 15.9825    │
│      ┆            ┆ BASKET      ┆ MARIE       ┆   ┆            ┆            ┆       ┆            │
│ Thu  ┆ 2024-04-11 ┆ OCEAN       ┆ CAP SAINTE  ┆ … ┆ 2.199      ┆ 0.0        ┆ 7.5   ┆ 16.4925    │
│      ┆            ┆ BASKET      ┆ MARIE       ┆   ┆            ┆            ┆       ┆            │
│ Sat  ┆ 2024-04-13 ┆ OCEAN       ┆ ITSAS TXORI ┆ … ┆ 3.459      ┆ 3.459      ┆ 7.5   ┆ 38.91375   │
│      ┆            ┆ BASKET      ┆             ┆   ┆            ┆            ┆       ┆            │
│ …    ┆ …          ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …     ┆ …          │
│ Sun  ┆ 2025-04-27 ┆ OCEAN       ┆ FRANCHE     ┆ … ┆ 3.003      ┆ 0.463      ┆ 7.5   ┆ 35.52      │
│      ┆            ┆ BASKET      ┆ TERRE       ┆   ┆            ┆            ┆       ┆            │
│ Sun  ┆ 2025-04-27 ┆ OCEAN       ┆ LAYLA       ┆ … ┆ 8.336      ┆ 6.631      ┆ 7.5   ┆ 118.64625  │
│      ┆            ┆ BASKET      ┆             ┆   ┆            ┆            ┆       ┆            │
│ Sun  ┆ 2025-04-27 ┆ OCEAN       ┆ VASCO       ┆ … ┆ 2.971      ┆ 2.971      ┆ 7.5   ┆ 44.565     │
│      ┆            ┆ BASKET      ┆             ┆   ┆            ┆            ┆       ┆            │
│ Tue  ┆ 2025-04-29 ┆ OCEAN       ┆ VASCO       ┆ … ┆ 5.291      ┆ 5.291      ┆ 7.5   ┆ 59.52375   │
│      ┆            ┆ BASKET      ┆             ┆   ┆            ┆            ┆       ┆            │
│ Wed  ┆ 2025-04-30 ┆ OCEAN       ┆ FRANCHE     ┆ … ┆ 6.588      ┆ 0.0        ┆ 7.5   ┆ 49.41      │
│      ┆            ┆ BASKET      ┆ TERRE       ┆   ┆            ┆            ┆       ┆            │
└──────┴────────────┴─────────────┴─────────────┴───┴────────────┴────────────┴───────┴────────────┘