In [5]:
import polars as pl

In [1]:
from dataframe.bin_dispatch import full_scows

In [7]:
full_scows.filter(pl.col("date").dt.month().eq(6).and_(pl.col("date").dt.year().eq(2025))).collect()

shape: (6, 11)
┌──────────┬────────────┬─────────────┬────────────┬───┬────────────┬─────────┬───────┬────────────┐
│ day_name ┆ date       ┆ customer    ┆ movement_t ┆ … ┆ num_of_sco ┆ tonnage ┆ Price ┆ total_pric │
│ ---      ┆ ---        ┆ ---         ┆ ype        ┆   ┆ ws         ┆ ---     ┆ ---   ┆ e          │
│ str      ┆ date       ┆ str         ┆ ---        ┆   ┆ ---        ┆ f64     ┆ f64   ┆ ---        │
│          ┆            ┆             ┆ str        ┆   ┆ i64        ┆         ┆       ┆ f64        │
╞══════════╪════════════╪═════════════╪════════════╪═══╪════════════╪═════════╪═══════╪════════════╡
│ Fri      ┆ 2025-06-06 ┆ ECHEBASTAR  ┆ IPHS       ┆ … ┆ 78         ┆ 73.625  ┆ 3.5   ┆ 257.6875   │
│          ┆            ┆             ┆ Delivery   ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ of Full    ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ Scows to…  ┆   ┆            ┆         ┆       ┆            │
│ Mon      ┆ 2025-06-09 ┆ ECHEBASTAR  ┆ IPHS       ┆ … ┆ 182        ┆ 171.208 ┆ 3.5   ┆ 599.228    │
│          ┆            ┆             ┆ Delivery   ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ of Full    ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ Scows to…  ┆   ┆            ┆         ┆       ┆            │
│ Tue      ┆ 2025-06-10 ┆ ECHEBASTAR  ┆ IPHS       ┆ … ┆ 182        ┆ 172.67  ┆ 3.5   ┆ 604.345    │
│          ┆            ┆             ┆ Delivery   ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ of Full    ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ Scows to…  ┆   ┆            ┆         ┆       ┆            │
│ Wed      ┆ 2025-06-11 ┆ ECHEBASTAR  ┆ IPHS       ┆ … ┆ 46         ┆ 43.955  ┆ 3.5   ┆ 153.8425   │
│          ┆            ┆             ┆ Delivery   ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ of Full    ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ Scows to…  ┆   ┆            ┆         ┆       ┆            │
│ Mon      ┆ 2025-06-23 ┆ INPESCA S.A ┆ IPHS       ┆ … ┆ 111        ┆ 106.0   ┆ 3.5   ┆ 371.0      │
│          ┆            ┆             ┆ Delivery   ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ of Full    ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ Scows to…  ┆   ┆            ┆         ┆       ┆            │
│ Tue      ┆ 2025-06-24 ┆ INPESCA S.A ┆ IPHS       ┆ … ┆ 109        ┆ 104.268 ┆ 3.5   ┆ 364.938    │
│          ┆            ┆             ┆ Delivery   ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ of Full    ┆   ┆            ┆         ┆       ┆            │
│          ┆            ┆             ┆ Scows to…  ┆   ┆            ┆         ┆       ┆            │
└──────────┴────────────┴─────────────┴────────────┴───┴────────────┴─────────┴───────┴────────────┘

In [1]:
from dataframe.miscellaneous import misc

In [12]:
misc.filter(pl.col("operation_type").str.contains("Cargo").and_(pl.col("date").dt.month().eq(6))).collect()

shape: (6, 13)
┌──────┬────────────┬─────────────┬─────────────┬───┬─────────┬──────────┬────────────┬────────────┐
│ day  ┆ date       ┆ movement_ty ┆ customer    ┆ … ┆ bins_in ┆ bins_out ┆ static_loa ┆ overtime_t │
│ ---  ┆ ---        ┆ pe          ┆ ---         ┆   ┆ ---     ┆ ---      ┆ der        ┆ onnage     │
│ enum ┆ date       ┆ ---         ┆ str         ┆   ┆ i64     ┆ i64      ┆ ---        ┆ ---        │
│      ┆            ┆ str         ┆             ┆   ┆         ┆          ┆ f64        ┆ f64        │
╞══════╪════════════╪═════════════╪═════════════╪═══╪═════════╪══════════╪════════════╪════════════╡
│ PH   ┆ 2025-06-19 ┆ OUT         ┆ INPESCA S.A ┆ … ┆ 0       ┆ -7       ┆ 0.0        ┆ 0.0        │
│ Mon  ┆ 2025-06-23 ┆ OUT         ┆ DARDANEL    ┆ … ┆ 0       ┆ -242     ┆ 0.0        ┆ 0.0        │
│ Mon  ┆ 2025-06-23 ┆ OUT         ┆ INPESCA S.A ┆ … ┆ 0       ┆ -34      ┆ 0.0        ┆ 0.0        │
│ Tue  ┆ 2025-06-24 ┆ OUT         ┆ DARDANEL    ┆ … ┆ 0       ┆ -294     ┆ 0.0        ┆ 0.0        │
│ Wed  ┆ 2025-06-25 ┆ OUT         ┆ DARDANEL    ┆ … ┆ 0       ┆ -359     ┆ 0.0        ┆ 0.0        │
│ Thu  ┆ 2025-06-26 ┆ OUT         ┆ DARDANEL    ┆ … ┆ 0       ┆ -360     ┆ 0.0        ┆ 116.88     │
└──────┴────────────┴─────────────┴─────────────┴───┴─────────┴──────────┴────────────┴────────────┘

In [11]:
empty_stock = r"C:\Users\gmounac\Downloads\pti_july.json"

In [37]:
pl.read_json(empty_stock).with_columns(size=pl.lit("40'")).with_columns(
    shipping_line=pl.col("shipping_line").str.replace("MAERSK", "MAERSKLINE")
).select(
    ["date_plugin", "container_number", "size", "set_point", "unit_manufacturer"]
)

shape: (386, 11)
┌───────────────┬──────────────┬───────────┬──────────────┬───┬─────────┬────────┬──────────┬──────┐
│ date_plugin   ┆ container_nu ┆ set_point ┆ unit_manufac ┆ … ┆ sticker ┆ status ┆ duration ┆ size │
│ ---           ┆ mber         ┆ ---       ┆ turer        ┆   ┆ ---     ┆ ---    ┆ ---      ┆ ---  │
│ str           ┆ ---          ┆ str       ┆ ---          ┆   ┆ str     ┆ str    ┆ str      ┆ str  │
│               ┆ str          ┆           ┆ str          ┆   ┆         ┆        ┆          ┆      │
╞═══════════════╪══════════════╪═══════════╪══════════════╪═══╪═════════╪════════╪══════════╪══════╡
│ 2025-06-01    ┆ MMAU1354770  ┆ -25       ┆ Starcool     ┆ … ┆ PASS    ┆ PASSED ┆ PT69360S ┆ 40'  │
│ 15:45:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ 2025-06-01    ┆ SUDU6159642  ┆ -25       ┆ Daikin       ┆ … ┆ RED     ┆ FAILED ┆ PT69360S ┆ 40'  │
│ 15:45:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ 2025-06-01    ┆ MNBU4216558  ┆ -25       ┆ Starcool     ┆ … ┆ PASS    ┆ PASSED ┆ PT69360S ┆ 40'  │
│ 15:45:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ 2025-06-01    ┆ MCAU6047036  ┆ -25       ┆ Daikin       ┆ … ┆ RED     ┆ FAILED ┆ PT69360S ┆ 40'  │
│ 15:45:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ 2025-06-01    ┆ SUDU8073698  ┆ -35       ┆ Thermoking   ┆ … ┆ PASS    ┆ PASSED ┆ PT69360S ┆ 40'  │
│ 15:45:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ …             ┆ …            ┆ …         ┆ …            ┆ … ┆ …       ┆ …      ┆ …        ┆ …    │
│ 2025-06-30    ┆ MNBU3391983  ┆ -25       ┆ Starcool     ┆ … ┆ PASS    ┆ PASSED ┆ PT26580S ┆ 40'  │
│ 08:25:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ 2025-06-30    ┆ MNBU4073523  ┆ -25       ┆ Starcool     ┆ … ┆ TBR     ┆ FAILED ┆ PT26580S ┆ 40'  │
│ 08:25:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ 2025-06-30    ┆ MNBU9186395  ┆ -25       ┆ Starcool     ┆ … ┆ PASS    ┆ PASSED ┆ PT26580S ┆ 40'  │
│ 08:25:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ 2025-06-30    ┆ MNBU3749634  ┆ -25       ┆ Starcool     ┆ … ┆ RED     ┆ FAILED ┆ PT26580S ┆ 40'  │
│ 08:25:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
│ 2025-06-30    ┆ MNBU4340126  ┆ -25       ┆ Starcool     ┆ … ┆ PASS    ┆ PASSED ┆ PT26580S ┆ 40'  │
│ 08:25:00      ┆              ┆           ┆              ┆   ┆         ┆        ┆          ┆      │
└───────────────┴──────────────┴───────────┴──────────────┴───┴─────────┴────────┴──────────┴──────┘

In [28]:
eform = pl.read_json(empty_stock).select(
    pl.col("date_plugin").str.to_datetime("%Y-%m-%d %H:%M:%S"),
    pl.col("container_number"),
)


eform.shape

(386, 2)

In [ ]:
invoice = (
    pti.filter(
        pl.col("datetime_start")
        .dt.year()
        .eq(2025)
        .and_(pl.col("datetime_start").dt.month().eq(6))
    )
    .with_columns(
        container_number=pl.col("container_number").cast(pl.Utf8),
        date_plugin=pl.col("datetime_start"),
    )
    .select(["date_plugin", "container_number", "status"])
    .collect()
)


invoice.shape

(379, 3)

In [ ]:
eform.join(
    invoice, on=["date_plugin", "container_number"], how="full"
).write_clipboard()